on:
  release:
    types: [created]
jobs:
  npm:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master

      - uses: actions/setup-node@v1
        with:
          node-version: "16.x"
          registry-url: "https://registry.npmjs.org"

      - name: Install npm dependencies
        run: |
          npm i --location=global typescript pnpm
          pnpm i -r

      - name: Build package
        run: tsc -p ./packages/ui/tsconfig-cjs.json

      - name: Change dir and update version
        run: |
          cd ./packages/ui/dist
          npm version patch

      - name: Publish tag to npm
        if: contains(github.ref, 'tags')
        run: npm publish --access=public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}

      - uses: actions/setup-node@v1
        with:
          registry-url: "https://npm.pkg.github.com"

      - name: Publish tag to GPR
        run: npm publish --access=public
        env:
          NODE_AUTH_TOKEN: ${{ github.token }}
